name: dera_x_neddy
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  gap: ^3.0.1
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.1.7
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  very_good_analysis: ^5.0.0

flutter_gen:
  output: lib/assets/
  line_length: 80
  integrations:
    flutter_svg: true
  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svgs/
    - assets/fonts/